apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daybreak-dev-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/redhat-guidehouse-daybreak/openshift-fhirserver-charts.git
      revision: HEAD
      branch: main
      directories:
        - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: daybreak-dev-app
      source:
        repoURL: placeholder-for-git-repo-url-see-overlays
        targetRevision: HEAD
        sourceBranch: main
        path: '{{path}}'
        helm:
          values: |
            zync_password: to-be-replaced-by-script
      destination:
        server: https://kubernetes.default.svc
        namespace: daybreak-dev
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - Replace=false
      ignoreDifferences:
      - group: route.openshift.io
        kind: Route
        jsonPointers:
          - /spec/host
    