apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: daybreak-dev-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/redhat-guidehouse-daybreak/openshift-fhirserver-charts.git
      revision: HEAD
      branch: main
      directories:
        - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: daybreak-dev-app
      source:
        repoURL: https://github.com/redhat-guidehouse-daybreak/openshift-fhirserver-charts.git
        targetRevision: main
        sourceBranch: main
        path: '{{path}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - ../../environments/dev/{{path.basename}}/values.yaml
          values: |
            zync_password: to-be-replaced-by-script
            environment: dev
      destination:
        server: https://kubernetes.default.svc
        namespace: daybreak-dev
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - Replace=false
      ignoreDifferences:
      - group: route.openshift.io
        kind: Route
        jsonPointers:
          - /spec/host
      - group: apps.openshift.io
        kind: DeploymentConfig
        name: psql-fhir
        jsonPointers:
          - /spec/template/spec/containers/0/image
      - group: apps.openshift.io
        kind: DeploymentConfig
        name: kafdrop
        jsonPointers:
          - /spec/template/spec/containers/0/image
        