apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daybreak-app-of-apps
spec:
  destination:
    namespace: daybreak-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: patch-me-see-overlays
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
