apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fhir-server-charts-dev
spec:
  generators:
  - git:
      repoURL: https://github.com/redhat-guidehouse-daybreak/openshift-fhirserver-charts.git
      revision: HEAD
      branch: main
      directories:
        - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: fhir-server-app
      source:
        repoURL: placeholder-for-git-repo-url-see-overlays
        targetRevision: HEAD
        sourceBranch: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: daybreak-dev
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: route.openshift.io
        kind: Route
        jsonPointers:
          - /spec/host
      