apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fhir-server-charts-dev
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: patient-viewer-dev
          namespace: patient-viewer-dev
          project: patient-viewer-dev
      # - cluster: engineering-prod
      #   url: https://2.4.6.8
      # - cluster: finance-preprod
      #   url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-daybreak'
    spec:
      project: default
      source:
        repoURL: https://github.com/redhat-guidehouse-daybreak/openshift-fhirserver-charts.git
        targetRevision: HEAD
        path: charts
      destination:
        server: '{{url}}'
        namespace: fhir-server-dev