apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 3scale-app-proj.yaml
  - 3scale-app.yaml
  - fhir-server-app-proj.yaml
  # - daybreak-app-of-apps.yaml
  # - patient-viewer-app-proj.yaml
  # - patient-viewer-app.yaml
  - fhir-server-charts-applicationset.yaml