apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: patient-viewer
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: patient-viewer-dev
              namespace: patient-viewer-dev
              project: patient-viewer-dev
              path: environments/dev/patient-viewer/overlays/default/
          #- cluster: local
          #  url: https://kubernetes.default.svc
          #  values:
          #    name: patient-viewer-test
          #    namespace: patient-viewer-test
          #    project: patient-viewer-test
          #    path: environments/test/patient-viewer/overlays/default/
          #- cluster: local
          #  url: https://kubernetes.default.svc
          #  values:
          #    name: patient-viewer-prod
          #    namespace: patient-viewer-prod
          #    project: patient-viewer-prod
          #    path: environments/prod/patient-viewer/overlays/default/
  template:
    metadata:
      name: '{{values.name}}'
    spec:
      destination:
        namespace: '{{values.namespace}}'
        server: https://kubernetes.default.svc
      project: '{{values.project}}'
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-tenant-overlays
        targetRevision: patch-me-see-tenant-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
