apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patient-viewer-dev
spec:
  destination:
    namespace: patient-viewer-dev
    server: https://kubernetes.default.svc
  project: patient-viewer-dev
  source:
    path: environments/dev/patient-viewer/overlays/default/
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true