apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daybreak-gitops

bases:
  - ../../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
    path: patch-applicationset-repo-revision.yaml
