kind: List
apiVersion: v1
namespace: fhir 
items:
  
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaTopic
    metadata:
        name: kakfa-connect-offsets
        namespace: fhir
        labels:
            strimzi.io/cluster: kafka-cluster
    spec:
        partitions: 25
        replicas: 3
        config: {"cleanup.policy": "compact"}            
  
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaTopic
    metadata:
        name: kakfa-connect-configs
        namespace: fhir
        labels:
            strimzi.io/cluster: kafka-cluster
    spec:
        partitions: 1
        replicas: 3
        config: {"cleanup.policy": "compact"}            
  
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaTopic
    metadata:
        name: kakfa-connect-status
        namespace: fhir
        labels:
            strimzi.io/cluster: kafka-cluster
    spec:
        partitions: 5
        replicas: 3
        config: {"cleanup.policy": "compact"}