apiVersion: v2
name: kafdrop

description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "kafdrop"
    version: "1.16.0"
    repository: "file://../../components/charts/kafdrop/"
 