apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: daybreak
  namespace: daybreak-dev
spec:
  orgName: daybreak
---
apiVersion: v1
kind: Secret
metadata:
  name: 3scale-developer-user-secret
  namespace: daybreak-dev
data:
  password: YWRtaW4jMTIz
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: daybreak
  namespace: daybreak-dev
spec:
  developerAccountRef:
    name: daybreak
  email: cpeng@guidehouse.com
  passwordCredentialsRef:
    name: 3scale-developer-user-secret
  role: admin
  username: daybreak