apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - system-storage.yaml
  - api-manager.yaml
  - developer-user-sealed-secret.yaml
  - account.yaml
  - vaivc-backend.yaml
  - vaivc-product.yaml