apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: va-ivc
  namespace: daybreak-dev
spec:
  name: va-ivc
  systemName: va-ivc
  applicationPlans:
    basic:
      name: daybreak-basic
      published: true
  backendUsages:
    va-ivc:
      path: /
  mappingRules:
    - httpMethod: GET
      pattern: "/"
      increment: 1
      metricMethodRef: hits
  policies:
    - name: cors
      version: builtin
      enabled: true
      configuration: {
        "allow_headers": [
          "*"
        ],
        "allow_methods": [
          "GET", "POST", "PUT"
        ],
        "allow_origin": "*",
      }
    - name: apicast
      version: builtin
      enabled: true
      configuration: {}
  deployment:
    apicastHosted:
      authentication:
        oidc:
          issuerType: "keycloak"
          issuerEndpoint: "https://daybreak:deysecret@mykeycloack.example.com/auth/realms/myrealm"
          authenticationFlow:
            standardFlowEnabled: true
            implicitFlowEnabled: false
            serviceAccountsEnabled: true
            directAccessGrantsEnabled: false
          jwtClaimWithClientID: "azp"
          jwtClaimWithClientIDType: "plain"
          credentials: headers