apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/redhat-guidehouse-daybreak/Patient-Viewer.git
    labels:
      app: patient-viewer-dev
      app.kubernetes.io/component: patient-viewer-dev
      app.kubernetes.io/instance: patient-viewer-dev
      app.kubernetes.io/name: patient-viewer-dev
      app.kubernetes.io/part-of: patient-viewer-dev
    name: patient-viewer-dev
    namespace: patient-viewer-dev
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: patient-viewer-dev
      deployment: patient-viewer-dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
