apiVersion: v1
kind: Service
metadata:
  name: patient-viewer-dev
  namespace: daybreak-dev
spec:
  selector:
    app: patient-viewer-dev
    deployment: patient-viewer-dev
  ports:
  - port: 8080
    targetPort: 8080
