apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: keycloak
    path: patch-domain.yaml